### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Parkand** [mahdiit/balesharp#1]
سلام
مشکل بسته شدن کانکشن سوکت رو چطور میشه رفع کرد
تایم اوت یا چیزی شبیه به اون داره یا نه؟

**Comment by mahdiit** [comment]
خیر در مدل سوکت کانکشن بسته شدن ارتباط از طریق سرور انجام میشود
برای همین شما باید هنگام ارسال پیام چک کنید که 
ارتباط برقرار هست یا نه

برای مثال خیلی از ارتباطات سوکت کانکشن حداکثر تا 24 ساعت باز خواهند ماند
برای همین باید اپ خود رو طوری طراحی کنید که در صورت بسته بودن ارتباط مجددا کانکشن دیگری باز نماید
