### ISSUE TITLE
ارسال جیسون اشتباه

### ISSUE THREAD

**Issue by DLMANSOFT** [mahdiit/balesharp#2]
سلام
من یک فایل خالی به جای جیسون با برنامه به سمت سرور فرستادم ، الان نه ربات کار میکنه
نه ربات پدر (botfather) به درخواست من جواب میده
چیکار باید بکنم درست بشه ؟

**Comment by mahdiit** [comment]
دوست گرامی وقتی پیام اشتباه به سرور ارسال کردین سرور از سمت خودش ارتباط استریم را میبندد
شما باید مجددا اقدام به باز کردن سوکت کانکشن جدید نمایید

**Comment by DLMANSOFT** [comment]
ظاهرا دیروز خود سرورهای بله مشکل داشت ، چون بعد از بازکردن سوکت ، موقع ارسال اطلاعات مجدد سوکت بسته میشد.
بررسی کردم و متوجه شده خود ربات پدر نیز کارنمیکند و به درخواست های کاربران پاسخ نمی‌دهد.
امروز این مشکل حل شده و قابل استفاده است.

سپاس از راهنمایی شما
